plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm' version '1.9.23'
    id "signing"
//    id 'io.github.gradle-nexus.publish-plugin' version '2.0.0'
}

ext {
    forge_server_jetty_version = '22.1.0'
}

apply plugin: 'maven-publish'

group = 'com.bolyartech.forge.server'
version forge_server_jetty_version

repositories {
    mavenCentral()
//    mavenLocal()
}

ext.jettyVersion = '12.1.2'

dependencies {
//    api project(':forge-server')
    api 'com.bolyartech.forge.server:forge-server:22.1.0'
    api "org.eclipse.jetty.ee10:jetty-ee10-webapp:$jettyVersion"
    api "org.eclipse.jetty.ee10:jetty-ee10-servlet:$jettyVersion"
    api "org.eclipse.jetty.ee10:jetty-ee10-servlets:$jettyVersion"

    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

test {
    useJUnitPlatform()
}


tasks.withType(Javadoc).all {
    enabled = false
}


task javadocJar(type: Jar) {
    classifier = 'javadoc'
    from javadoc
}

task sourcesJar(type: Jar) {
    classifier = 'sources'
    from sourceSets.main.allSource
}

artifacts {
    archives javadocJar, sourcesJar
}


publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId 'com.bolyartech.forge.server'
            artifactId 'forge-server-jetty'
            version forge_server_jetty_version
            artifact sourcesJar
            artifact javadocJar

            pom {
                name = 'Forge Server Jetty'
                packaging = 'jar'
                // optionally artifactId can be defined here
                description = 'Jetty implementation of Forge Server'
                url = 'https://github.com/ogrebgr/forge-server-jetty'

                scm {
                    connection = 'scm:git:https://github.com/ogrebgr/forge-server-jetty.git'
                    developerConnection = 'scm:git:https://github.com/ogrebgr/forge-server-jetty.git'
                    url = 'https://github.com/ogrebgr/forge-server-jetty'
                }

                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }

                developers {
                    developer {
                        id = 'ogremir'
                        name = 'Ognyan Bankov'
                        email = 'bankov@bolyartech.com'
                    }
                }
            }
        }
    }
}

//nexusPublishing {
//    repositories {
//        sonatype {
//            stagingProfileId.set("com.bolyartech")
//            nexusUrl.set(uri("https://ossrh-staging-api.central.sonatype.com/service/local/"))
//            snapshotRepositoryUrl.set(uri("https://central.sonatype.com/repository/maven-snapshots/"))
//            username = findProperty('ossrhUsername')
//            password = findProperty('ossrhPassword')
//        }
//    }
//}

signing {
    sign publishing.publications.mavenJava
}

kotlin {
    jvmToolchain(17)
}